# Generated by Django 3.0.5 on 2020-05-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ventas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('cantidad', models.IntegerField(default=0, verbose_name='cantidad')),
                ('fecha', models.DateField(verbose_name='fecha')),
            ],
        ),
    ]
