# Generated by Django 3.0.5 on 2020-05-29 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion_de_lote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('lote', models.IntegerField(verbose_name='lote')),
                ('fecha_de_emision', models.DateField(verbose_name='fecha de emision')),
                ('fecha_de_fabricacion', models.DateField(verbose_name='fecha de fabricacion')),
                ('fecha_de_vencimiento', models.DateField(verbose_name='fecha de vencimiento')),
                ('gerente_encargado', models.CharField(max_length=255, verbose_name='gerente encargado')),
                ('observaciones', models.CharField(max_length=255, verbose_name='observaciones')),
                ('orden_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistica.Orden_de_produccion')),
            ],
        ),
    ]
