# Generated by Django 3.0.5 on 2020-06-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produccion_de_lote',
            old_name='orden_id',
            new_name='Orden_de_produccion',
        ),
    ]
