# Generated by Django 3.0.5 on 2020-05-29 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen_insumos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('tipo', models.CharField(max_length=255, verbose_name='tipo')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('medida', models.IntegerField(default=0, verbose_name='medida')),
            ],
        ),
        migrations.CreateModel(
            name='Almacen_pt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('cantidad', models.IntegerField(default=0, verbose_name='cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('medida', models.IntegerField(default=0, verbose_name='medida')),
                ('fecha_compra', models.DateField(verbose_name='fecha de compra')),
            ],
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_despacho', models.DateField(verbose_name='fecha de despacho')),
                ('gerente_encargado', models.CharField(max_length=255, verbose_name='gerente encargado')),
            ],
        ),
        migrations.CreateModel(
            name='Formula_maestra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('cantidad', models.FloatField(verbose_name='cantidad')),
            ],
        ),
        migrations.CreateModel(
            name='Orden_de_produccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('lote', models.IntegerField(verbose_name='lote')),
                ('Orden_de_produccion', models.IntegerField(verbose_name='orden de produccion')),
                ('fecha_de_emision', models.DateField(verbose_name='fecha de emision')),
                ('gerente_encargado', models.CharField(max_length=255, verbose_name='gerente encargado')),
                ('observaciones', models.CharField(max_length=255, verbose_name='observaciones')),
                ('Formula_maestra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistica.Formula_maestra')),
            ],
        ),
    ]
