# Generated by Django 3.0.5 on 2020-06-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlop', '0002_auto_20200608_2240'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Almacen_insumos',
            new_name='Almacen_insumo',
        ),
        migrations.RenameModel(
            old_name='Compras',
            new_name='Compra',
        ),
    ]
