# Generated by Django 3.0.5 on 2020-07-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_auto_20200608_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('lote_insumos', models.IntegerField(verbose_name='lote de insumos')),
                ('cantidad', models.IntegerField(verbose_name='unidad de medida')),
                ('orden_produccion', models.IntegerField(verbose_name='orden de produccion')),
                ('lote_produccion', models.IntegerField(verbose_name='produccion de lote')),
                ('lote_terminado', models.IntegerField(verbose_name='codigo de producto terminado')),
                ('fecha_de_emision', models.DateField(verbose_name='fecha de emision')),
                ('lote_venta', models.IntegerField(verbose_name='numero de factura')),
                ('lote_compra', models.IntegerField(verbose_name='orden de despacho')),
                ('status', models.BooleanField(choices=[(1, 'aprobado'), (2, 'rechazado')], default=1)),
                ('gerente_encargado', models.CharField(max_length=255, verbose_name='gerente encargado')),
            ],
        ),
    ]
