# Generated by Django 3.0.5 on 2020-07-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_trazabilidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='trazabilidad',
            name='orden_de_despacho',
            field=models.IntegerField(default=0, verbose_name='orden de despacho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trazabilidad',
            name='lote_compra',
            field=models.IntegerField(verbose_name='codigo de compra'),
        ),
    ]
