# Generated by Django 3.0.5 on 2020-07-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_auto_20200722_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orden_de_produccion',
            options={'verbose_name': 'Orden de produccion', 'verbose_name_plural': 'Ordenes de produccion'},
        ),
    ]
