# Generated by Django 3.0.5 on 2020-05-29 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision_produccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Revision_compras',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.BooleanField()),
                ('compras_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='logistica.Compras')),
            ],
        ),
    ]
