# Generated by Django 3.0.5 on 2020-06-09 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0001_initial'),
        ('controlop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Revision_compras',
            new_name='Revision_compra',
        ),
    ]
